<?php

// This file was generated by running "composer dump-env dev"

return array(
    'APP_ENV' => 'dev',
    'APP_SECRET' => '08205ba33b648da09e7c5c9157e1129a',
    'MAILER_DSN' => 'smtp://localhost:1025',
    'DATABASE_URL' => 'mysql://root:@localhost:3306/tekoma',
    'HCAPTCHA_SITEKEY' => '8ff64c97-f0f7-4e42-a700-1df57e144185',
    'HCAPTCHA_SECRET_KEY' => '0x66cA099A700B07dd94fFcB5C931dBDB8093018BA',
    'STRIPE_PUBLIC_KEY_TEST' => 'pk_test_51JwqrRH4PMPk56yFjIO5aOK2wzuD4SeAGmWOuz0JciHR0Xr2a5MbMYSqX3eLQRrsjvvCxYp9537kEjq5YUnh7X8E00aqzhDpTT',
    'STRIPE_SECRET_KEY_TEST' => 'sk_test_51JwqrRH4PMPk56yFSuROHD9dadZpgcqq4ICXmF4a3qt2dhwkdJ66GBHDkbw6oDuOUAexsv8JHaSbypTWS6JIYfgR007eMNfU9e',

);
